from mysql:8.0

WORKDIR /app

# Add crontab file in the cron directory
ADD crontab /etc/cron.d/backup-cron
ADD initdb.sql /docker-entrypoint-initdb.b
ADD /script/bddBackup /app

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/backup-cron

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log